### ISSUE TITLE
using `--host_override` causes nil pointer dereference

### ISSUE THREAD

**Issue by D3N14L** [Lusitaniae/apache_exporter#97]
When using the host_override argument and accessing the metrics endpoint the process dies with a nil pointer dereference:
``` 
time="2021-04-13T12:43:47Z" level=info msg="Starting apache_exporter (version=, branch=, revision=)" source="apache_exporter.go:360"
time="2021-04-13T12:43:47Z" level=info msg="Build context (go=go1.13.9, user=, date=)" source="apache_exporter.go:361"
time="2021-04-13T12:43:47Z" level=info msg="Starting Server: :9117" source="apache_exporter.go:362"
time="2021-04-13T12:43:47Z" level=info msg="Collect from: \"http://myapp.svc.cluster.local/server-status/?auto\"" source="apache_exporter.go:363"
time="2021-04-13T12:43:47Z" level=info msg="listening and wait for graceful stop" source="apache_exporter.go:367"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x85b1c6]

goroutine 14 [running]:
main.(*Exporter).collect(0xc000176000, 0xc000062de0, 0xc000062ea0, 0x0)
	/app/apache_exporter.go:190 +0xa6
main.(*Exporter).Collect(0xc000176000, 0xc000062de0)
	/app/apache_exporter.go:334 +0x91
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:443 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:454 +0x57d
```

Tested on 0.7.0 and 0.8.0.
The host_override used here is: `--host_override="status"`

We are using the bitnami image for 0.8.0.

EDIT:
This happens only when we use the exporter in kubernetes and configure the host_override arguments with quotation marks:
```
args:
 - --host_override="status"
 ```

**Comment by Lusitaniae** [comment]
Have you found a solution to this problem?

**Comment by D3N14L** [comment]
As the "EDIT" implies: Try it without the quotation marks.
If i recall it correctly it should work that way:
```
args:
 - --host_override=status
```

**Comment by Lusitaniae** [comment]
Good to hear, 

thanks for the update!
